// <auto-generated />
namespace DX.Loan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class _201814_modiftyEntity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201814_modiftyEntity));
        
        string IMigrationMetadata.Id
        {
            get { return "201801040717026_2018-1-4_modiftyEntity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
