// <auto-generated />
namespace DX.Loan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AbpZero_Initial_2018215 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AbpZero_Initial_2018215));
        
        string IMigrationMetadata.Id
        {
            get { return "201802151536495_AbpZero_Initial_2018-2-15"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
